### ISSUE TITLE
I love this project. Please merge to GCC asap

### ISSUE THREAD

**Issue by trcrsired** [Windows-on-ARM-Experiments/gcc-woarm64#16]
TY TY TY!!!

**Comment by eukarpov** [comment]
Thank you!
The first patch series has been merged recently to gcc upstream.
https://gcc.gnu.org/pipermail/gcc-patches/2024-April/thread.html#649261
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=13bad1ac7a6ea4dbbde67c69d31c218a2f2d7a5d

The second patch series is on the community review.
https://gcc.gnu.org/pipermail/gcc-patches/2024-April/thread.html#649685
