### ISSUE TITLE
Wrong value into BUILD_SYSTEM_HEADER_DIR (GCC BUG #115302)

### ISSUE THREAD

**Issue by carlo-bramini** [Windows-on-ARM-Experiments/gcc-woarm64#17]
From GCC Bug [115302](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115302)

I downloaded the latest sources of GCC from the repository and I tried to compile them for making the (experimental) aarch64-w64-mingw32 target.
Besides the target, the only important options for this issue are:
```
 --with-sysroot=/usr/aarch64-w64-mingw32/sys-root
 --enable-languages=c
```
on the command line.
Everything was fine until it stopped with this error:
```
The directory (BUILD_SYSTEM_HEADER_DIR) that should contain system headers does not exist:
  /usr/aarch64-w64-mingw32/sys-root/usr/include
make[2]: *** [Makefile:3446: stmp-fixinc] Error 1
```
But this is wrong because it must use:
```
 /usr/aarch64-w64-mingw32/sys-root/mingw/include
```
and not:
```
 /usr/aarch64-w64-mingw32/sys-root/usr/include
```
so this is the reason because it cannot find the headers.
At first sight, it seems the current code is using the default path for the native system headers.
Actually, existing x86 and x86_64 targets have configured `native_system_header_dir` to `/mingw/include` as you can see here into config.gcc from the mirror at GITHUB:

https://github.com/gcc-mirror/gcc/blob/f46eaad445e680034df51bd0dec4e6c7b1f372a4/gcc/config.gcc#L2274

but the same line doesn't exist into the section for the `aarch64-*-mingw*` as you can read here:

https://github.com/gcc-mirror/gcc/blob/f46eaad445e680034df51bd0dec4e6c7b1f372a4/gcc/config.gcc#L1272

So, in my opinion, simply adding this line:
```
native_system_header_dir=/mingw/include
```
into the above section should be enough for solving immediately this issue.
I don't know if this fix needs other changes to be made also into binutils, but probably not.
Thank you very much for your support.

**Comment by eukarpov** [comment]
Thanks, Carlo, for reporting the issue!
I saw this issue in GCC Bugzilla. However, I need to create an account there to reply, and it might take some time.
I'm glad you reported the issue here.

I would suggest fixing the issue in a different way.

1. Exclude `--with-sysroot=/usr/aarch64-w64-mingw32/sys-root` from the configuration.
2. Create a symlink for mingw in the toolchain folder before building GCC.

**Comment by eukarpov** [comment]
Another way to build the toolchain is as follows:

Clone this repository: https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build
Then, execute `./build.sh`.

The build process has been recently simplified, and these changes should be reflected on the main page soon.

**Comment by carlo-bramini** [comment]
> I would suggest fixing the issue in a different way.
> 
>     1. Exclude `--with-sysroot=/usr/aarch64-w64-mingw32/sys-root` from the configuration.
> 
>     2. Create a symlink for mingw in the toolchain folder before building GCC.

I discovered this issue because I tried to make a package for CYGWIN.
It uses its `cygport` tool for unpacking, compiling and packaging.
Everything can be surely done by using hand written code, but if it could be fixed it would make things a bit easier.

> Another way to build the toolchain is as follows:
> 
> Clone this repository: https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build Then, execute `./build.sh`.

I also compiled successfully all sources by using the script from the above page.

**Comment by eukarpov** [comment]
Thank you for clarifying the case. We will investigate the proper approach to using `--with-sysroot`.

**Comment by Blackhex** [comment]
@carlo-bramini Thank you for reporting the issue. I can verify that your suggested fix works and seems to be the poper one. We might fix it in this repository with #19.

By the way, what do you mean by

> I discovered this issue because I tried to make a package for CYGWIN. 

? The [https://cygwin.com/cgit/cygwin-packages/mingw64-x86_64-gcc/tree/mingw64-x86_64-gcc.cygport](https://cygwin.com/cgit/cygwin-packages/mingw64-x86_64-gcc/tree/mingw64-x86_64-gcc.cygport) does not use `--with-sysroot` ...

**Comment by Blackhex** [comment]
JFYI, MSYS2 uses this patch https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/0005-Windows-Don-t-ignore-native-system-header-dir.patch on top of the proposed solution.

**Comment by carlo-bramini** [comment]
> By the way, what do you mean by
> 
> > I discovered this issue because I tried to make a package for CYGWIN.
> 
> ? The https://cygwin.com/cgit/cygwin-packages/mingw64-x86_64-gcc/tree/mingw64-x86_64-gcc.cygport does not use `--with-sysroot` ...

Well, this information is not written into the `.cygport` files but it is handled by the scripts making the cygport tool.
When building the toolchain, this is provided by the `cygclass/toolchain.cygclass` script:
https://github.com/cygwin/cygport/blob/5f209bee5b6f5fe5256b81a02fecf7246b5bb512/cygclass/toolchain.cygclass#L76
and it is fed on the command line to configure script here:
https://github.com/cygwin/cygport/blob/5f209bee5b6f5fe5256b81a02fecf7246b5bb512/cygclass/toolchain.cygclass#L159
When building stuff to be used by `x86_64-w64-mingw32` or `i686-w64-mingw32`, it is expected that the sysroot will have `mingw` instead of `usr`, as you can see here:
https://github.com/cygwin/cygport/blob/5f209bee5b6f5fe5256b81a02fecf7246b5bb512/lib/syntax.cygpart#L221-L229 
probably just because this is what is expected to happen from `config.gcc` when doing mingw-w64 targets.

I have also read the comments at #19 about the patch applied by MSYS2... actually I have not experience with that change and I don't know which one is the best but, if I could say my opinion, perhaps it would be worth to reproduce the same, exact behaviour also for aarch64-w64-mingw32 as it is currently made for Intel targets in the main GCC at the time of writing, otherwise some troubles/malfunctions may rise suddently.

**Comment by eukarpov** [comment]
We have discussed this issue, and for now I would suggest you to use --native-system-header-dir=/mingw/include with --with-sysroot.

**Comment by eukarpov** [comment]
Based on the feedback https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/issues/24
"--native-system-header-dir=/mingw/include" is a working acceptable solution.
