### ISSUE TITLE
Question about x18 reservation

### ISSUE THREAD

**Issue by trcrsired** [Windows-on-ARM-Experiments/gcc-woarm64#18]
Does that mean the compiler can never use x18 again, or is it free to store and load x18 when registers are not enough?

I wrote algorithms like sha512, which heavily relies on using every register.

**Comment by Blackhex** [comment]
Hello.

Thank you for using our experimental toolchain. The X18 register is reserved for Windows operating system by Arm64 Windows ABI conventions (https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-170#integer-registers) and no user-space code should use it.
