### ISSUE TITLE
Windows on Riscv and Loongarch when?

### ISSUE THREAD

**Issue by trcrsired** [Windows-on-ARM-Experiments/gcc-woarm64#22]
Considering the geopolitical tension between the US and China, any thoughts on Windows support on Riscv and Loongarch? LLVM has already supported riscv64-windows-msvc, riscv64-windows-gnu, loongarch64-windows-msvc, loongarch64-windows-gnu for years.

I think Visual C++ should just stop developing and use LLVM/clang instead and just continue maintaining windows crt and stl. This reduces the cost in the long run.
In fact, Edge switched from EdgeHtml to Chromium was a huge success and I use it every day even on my android phone, oculus quest 2 and arch linux.

As long as we make binutils-gdb, gcc to support loongarch and riscv for windows, it should work just fine. Time for a border competition, since arm licensing is bad tbh.

Even existing things like ARM MTE do not work on MSVC but work on clang. We should just let llvm to do the job. MSVC is lack of progress for memory safety detections compared to GCC and LLVM for at least a decade.

The problem is that backend stuffs are not what microsoft could do. They are very vendor specific and only vendors know the details on how to optimize them. Visual C++ is not open-source and it generates poor code compared to GCC and LLVM. Considering even Intel has switched to LLVM, i think microsoft should give up too.

**Comment by trcrsired** [comment]
https://www.youtube.com/live/9N_o6T8sqaA?si=OLoX4z0_xIzXzN0j

LoongArch is very similar to riscv, even from the calling convention perspective. However, it has better default than riscv and it provides hardware-level x86 to LoongArch translation which means windows x86 emulation should work faster on LoongArch than ARM.

**Comment by trcrsired** [comment]
https://docs.kernel.org/arch/loongarch/introduction.html

**Comment by Peter0x44** [comment]
> LLVM has already supported riscv64-windows-msvc, riscv64-windows-gnu, loongarch64-windows-msvc, loongarch64-windows-gnu for years.

How can this be? Do you have a source for it?
riscv64 and loongarch windows is not a thing to my knowledge...
Linking linux kernel documentation isn't evidence of this because it is obviously for linux...

**Comment by Blackhex** [comment]
Hello. Thank you for your interest in trying the `aarch64-w64-mingw32` target cross-compilation toolchain. Because there does not seem to be anything actionable in the report, I am closing this issue. Please, let us know if there is anything from your perspecitve how we can improve the `aarch64-w64-mingw32` target.

Also note that we are using [https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/issues](https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/issues) repository as the main one containing the complete list of known issues.

**Comment by trcrsired** [comment]
> > LLVM has already supported riscv64-windows-msvc, riscv64-windows-gnu, loongarch64-windows-msvc, loongarch64-windows-gnu for years.
> 
> How can this be? Do you have a source for it? riscv64 and loongarch windows is not a thing to my knowledge... Linking linux kernel documentation isn't evidence of this because it is obviously for linux...

Yes, it has loongarch64-windows-msvc. Considering the riscv is nearly a dead end and the geopolitical tension between the US and China are getting worse. Loongarch support for windows should be a priority for microsoft.

In fact, microsoft should just give up msvc and use clang instead.

**Comment by trcrsired** [comment]
> > LLVM has already supported riscv64-windows-msvc, riscv64-windows-gnu, loongarch64-windows-msvc, loongarch64-windows-gnu for years.
> 
> How can this be? Do you have a source for it? riscv64 and loongarch windows is not a thing to my knowledge... Linking linux kernel documentation isn't evidence of this because it is obviously for linux...

loongarch
https://godbolt.org/z/qdarqh6br

riscv
https://godbolt.org/z/7MPqvs9s1

**Comment by trcrsired** [comment]
> Hello. Thank you for your interest in trying the `aarch64-w64-mingw32` target cross-compilation toolchain. Because there does not seem to be anything actionable in the report, I am closing this issue. Please, let us know if there is anything from your perspecitve how we can improve the `aarch64-w64-mingw32` target.
> 
> Also note that we are using https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/issues repository as the main one containing the complete list of known issues.

https://learn.microsoft.com/en-us/windows/win32/debug/pe-format

IMAGE_FILE_MACHINE_RISCV32
0x5032
RISC-V 32-bit address space
IMAGE_FILE_MACHINE_RISCV64
0x5064
RISC-V 64-bit address space
IMAGE_FILE_MACHINE_RISCV128
0x5128
RISC-V 128-bit address space



IMAGE_FILE_MACHINE_LOONGARCH32
0x6232
LoongArch 32-bit processor family
IMAGE_FILE_MACHINE_LOONGARCH64
0x6264
LoongArch 64-bit processor family



So even microsoft's own documents said PE supports loongarch and riscv. And it has to for UEFI support. I don't see anything wrong with releasing a loongarch version of windows + loongarch has hardware x86 translation.

https://github.com/trcrsired/RISCV-bad-LoongArch-good
